---
# tasks file for workstation-basic
#

# Block sites
- import_tasks: blocked-sites.yml

# # Configuration of Users
#- import_tasks: users.yml

# # System wide packages
#- import_tasks: packages.yml

# User specific packages
#- import_tasks: packages_aluno.yml

# System wide configuration
- import_tasks: system.yml

# Module that disable ethernet adapter
#- import_tasks: wifi.yml
#- import_tasks: msi-software.yml
- import_tasks: wipe-settings.yml



  






