- name: Ensure Basic softwares are installed via Chocolatey
  win_chocolatey:
      name: "{{ item }}"
      state: latest
  loop:
       - 7zip
       - googlechrome
       - firefox
       - vlc
       - libreoffice-still

- name: install lego EV3
  win_package: 
        path: http://10.1.255.17/EV3_Classroom_Windows_1.50_Global.msi
        state: present
        arguments:
                - /qn

- name: install dev tools
  win_chocolatey:
        name: "{{ item }}"
        state: latest
  loop:
        - vscode
        - vscode-arduino
        - codeblocks
        - python3
        - androidstudio
        - wireshark
        - netbeans
        - eclipse
        - arduino
        - nodejs
        - filezilla
        - putty
        - winscp
        - blender
        - winpcap        
        - mysql.workbench
        - pgadmin4
        - git
        - postman
        - inkscape
        - gimp
        - shotcut


- name: update pip
  win_shell: python.exe -m pip install --upgrade pip


- name: install nodejs packages
  win_shell: npm install express bootstrap moment                       
